### ISSUE TITLE
idk how to use it

### ISSUE THREAD

**Issue by yuki0bruh** [Vazity1337/Discord-Nitro-Generator#12]
i cant type in the main.py file please help

**Comment by s1mple-hub** [comment]
IDK

**Comment by Vazity1337** [comment]
To edit the file use notepad on windows or another text editor

**Comment by AzulVSTheWorld** [comment]
what do i do after that

**Comment by Vazity1337** [comment]
Im not gonna help people who dont even know how to edit a python file

**Comment by IIWare** [comment]
right click main.py, click open with > notepad
