### ISSUE TITLE
Discord error after trying to get Nitro from gift cards.

### ISSUE THREAD

**Issue by IIWare** [Vazity1337/Discord-Nitro-Generator#25]
Hi, I would like to get nitro but when I join from the generated link, the discord error with poo will show up:
![invalidddd](https://user-images.githubusercontent.com/66434686/102179637-8f0f9600-3eb8-11eb-8bf0-a1b7ce8b1654.PNG)
I don't know why, it will greatly be appreciated if someone can tell me why does this show up, thanks.

**Comment by Yash9729** [comment]
It ain't gonna work 
![image](https://user-images.githubusercontent.com/70028651/102301783-8d5bd600-3f7d-11eb-97c7-34a62e54f8dc.png)  as you can see it only shows some random texts

**Comment by IIWare** [comment]
@Yash9729 if it's not gonna work, then can you please tell me what's the use of the program if it cannot generate valid discord nitro codes?

**Comment by Yash9729** [comment]
It's only a nitro generator and the owner haven't mentioned whether it generates vaild codes or invalid

**Comment by KoopintheHub** [comment]
Yeah it just generates random words. Scam!

**Comment by Yash9729** [comment]
Simply there's no way to get free nitro

**Comment by HZ-0Z3R0** [comment]
> Yeah it just generates random words. Scam!

It's not a scam. Did the program ever say it would generate valid codes? If this was a program that could generate valid codes every time, Discord would go bankrupt and have terrible customer reviews. Think about it.

**Comment by HZ-0Z3R0** [comment]
> Simply there's no way to get free nitro

Of course this is true. Don't waste your time searching how to get free nitro. Just work at McDonalds and get 10 dollars and hour, seriously!

**Comment by RivRob** [comment]
true

**Comment by RivRob** [comment]
just work for the trash lol

**Comment by KoopintheHub** [comment]
> > Yeah it just generates random words. Scam!
> 
> It's not a scam. Did the program ever say it would generate valid codes? If this was a program that could generate valid codes every time, Discord would go bankrupt and have terrible customer reviews. Think about it.

Oh yeah true

**Comment by Yash9729** [comment]
> > Simply there's no way to get free nitro
> 
> Of course this is true. Don't waste your time searching how to get free nitro. Just work at McDonalds and get 10 dollars and hour, seriously!

I'm already having a nitro
