### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Poppyglitter17** [Vazity1337/Discord-Nitro-Generator#5]
How do you download and use this?

**Comment by Oof4** [comment]
think you go in releases

**Comment by Vazity1337** [comment]
To download click on code then download as zip

**Comment by tuxeroo** [comment]
how do you use this?

**Comment by tuxeroo** [comment]
i found out how to use this, but the codes won't work

**Comment by Vazity1337** [comment]
Make sure you have python and the requirements installed

**Comment by AzulVSTheWorld** [comment]
what are the requirments
