### ISSUE TITLE
???

### ISSUE THREAD

**Issue by lilcsz** [Vazity1337/Discord-Nitro-Generator#7]
1: You can't generate nitro with this. It's impossible
2: Need auto check for nitro

**Comment by Vazity1337** [comment]
Yes you can generate nitro codes that's what the code does and it's a
generator not a code checker

**Comment by Official-Husko** [comment]
> 
> 
> 1: You can't generate nitro with this. It's impossible
> 2: Need auto check for nitro

imagine being dumb like this dude

**Comment by lilcsz** [comment]
@Official-Husko Watching cartoon porn and saying this.....

**Comment by Official-Husko** [comment]
> 
> 
> @Official-Husko Watching cartoon porn and saying this.....

![image](https://user-images.githubusercontent.com/27901510/94496378-829e6a00-01f4-11eb-8bc5-9474151d70ff.png)

**Comment by Vazity1337** [comment]
> > 1: You can't generate nitro with this. It's impossible
> > 2: Need auto check for nitro
> 
> imagine being dumb like this dude

Perhaps you dont know what generators do it dosn't check nitro it generates code dumbass
